FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN npm run build 

EXPOSE 8080

CMD ["npm", "run", "dev"]

