# Dockerfile
FROM node:18

WORKDIR /app

COPY frontend/my-app/package*.json ./
RUN npm install

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN npm run build  # if React frontend

EXPOSE 8080

CMD ["npm", "run", "dev"]