name: Deploy Backend

on:
  push:
    branches:
      - integration
    paths:
      - 'backend/**' # Only triggers if backend files change

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/backend-repo/my-api:${{ github.sha }}
          docker build -t $IMAGE_NAME ./backend
          docker push $IMAGE_NAME

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: backend-service
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/backend-repo/my-api:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: '--allow-unauthenticated'
          env_vars: |
            MONGODB_URI=${{ secrets.MONGODB_URI }}